remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: LAIC Fantasy Football
description: "Large and In Charge" - Eric Ledner
show_downloads: false
